### ISSUE TITLE
redundant sphinx requirement autoprogram

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/pvl#47]
Autoprogram is automatically documenting argparser objects to document a CLI, but `pvl` doesn't seem to have any, so I think we should remove this added dependency from `docs/conf.py`

Thoughts? Did I miss something?

**Comment by AndrewAnnex** [comment]
Sounds like a yes to me, but we should probably also setup read the docs builds


I’ve also played around with GitHub actions recently, it should be relatively easy to build the docs within GitHub but that would tie the repo to GitHub a bit more tightly but maybe that isn’t a real issue 

-Andrew Annex

**Comment by rbeyer** [comment]
You're right that there is no single, main *pvl* executable that might have a CLI, but I added the two utilities, pvl_validate and pvl_translate, and they do have CLIs, so that's why I put autoprogram is in the docs/conf.py (it wasn't there before my 1.0.0-alpha merge).

I'm not sure what you mean, Andrew, Michael and I did sort out the readthedocs builds (I think), they are auto-running now when new commits and tags are merged into the repo.

**Comment by michaelaye** [comment]
Oh never mind then I must have searched wrong for argparser, see it now.
