### ISSUE TITLE
many tests fail on master in local dev

### ISSUE THREAD

**Issue by AndrewAnnex** [planetarypy/pvl#54]
I am trying to run tests in a new conda environment I made for developing PVL and was seeing many errors for functions I wasn't touching. So I checked out master (be90a3e5425875828ca70e8fc66c67992559c64c) and ran the tests and got the following error log. This is confusing as clearly travis is running fine. the log is from using the make file. 
[errors.log](https://github.com/planetarypy/pvl/files/4682907/errors.log)

**Comment by AndrewAnnex** [comment]
I closed this issue thinking it was just because of astropy, but many of the errors remain 
[errors.log](https://github.com/planetarypy/pvl/files/4682949/errors.log)

**Comment by rbeyer** [comment]
Looks like you're using PyCharm which can have some squirrely-ness if you don't set up the test environment "just so".  Looks to me like PyCharm is running the latest tests with an older version of pvl somehow.

You say you also ran from the Makefile at the command line, so that shouldn't have this problem, because if you're at the top level of the repo, when the tests import pvl, they should get the 'local' pvl (which is the git-checked-out code) and not some pvl that may be resident on your system in the paths that python searches.  Of course, this could also be one of those reasons to go to a 'src/'-based layout that Michael was championing.

**Comment by AndrewAnnex** [comment]
yeah I'll have to dig deep into this but as far as I could tell it was using the conda environments python..

**Comment by michaelaye** [comment]
that scenario actually could exactly be the src/ vs non-src layout testing problem, discussed here: https://docs.pytest.org/en/latest/goodpractices.html

**Comment by AndrewAnnex** [comment]
I think I confirmed that this is a python 3.8 issue, I'll post a pr soon with a new travis test to verify

**Comment by AndrewAnnex** [comment]
success, please check #55

**Comment by rbeyer** [comment]
Okay, so this doesn't have anything to do with the layout, but everything to do with Python 3.8, as Andrew discovered.

The most recent commit to master, be90a3e, passed "make test-all" locally because it was only tested against Python 3.6 and 3.7.  Similarly, the [Travis run for that build](https://travis-ci.org/github/planetarypy/pvl/builds/689394379), also did not test against 3.8, which is why it passed.  I didn't realize that pvl wasn't being tested against 3.8.  I typically develop in 3.6, and then let the tox tests flush out version issues, and in other projects I'm in, 3.8 *is* in the test loop.

If you checkout master, and add "py38" to tox.ini, you get these errors.  Well, at least that mystery is solved.  Now we just need to figure out what changed in 3.8 to cause this.  I can work on this, may take a few days for me to get back around to it.

**Comment by rbeyer** [comment]
I had some time listening to a telecon today and figured it out: the issue was related to a subtle change in the way the builtin float() worked with 3.8, combined with the fact that the pvl.Token class did not have a `__float__()` method, but did have an `__index__()` method.  

In the past, since pvl.Token didn't have `__float__()` when `float()` was called on it, it just defaulted to the `__float__()` method on its parent class: `str` which did the right thing.  In 3.8, if the object has an `__index__()` method (which pvl.Token did), `float()` will use that (to try and get an integer to convert to a float), but that didn't work out.  A simple implementation of a `__float__()` function on pvl.Token seems to be the trick.

PR later today or tomorrow.
