### ISSUE TITLE
Adding issue templates

### ISSUE THREAD

**Issue by jessemapel** [planetarypy/pvl#60]
The contributing guidelines say you should put your OS and environment information in your bug report. An issue template would help remind reporters to do this.

I really like this quaint template generator:

https://www.talater.com/open-source-templates/#/

**Comment by rbeyer** [comment]
That's a great idea, and a wonderful little site.

I tried to follow [the instructions](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository), but I don't see a "Features" setting to set up templates on the pvl repo.  Maybe I don't have the right permissions on the repo?  I can just commit files to the repo, but since it is a GitHub thing, I feel like we should run through their 'setup' process and then we can tweak things.

**Comment by AndrewAnnex** [comment]
it's in the github ui bia insights -> community -> add issue templates
https://github.com/planetarypy/pvl/issues/templates/edit

**Comment by rbeyer** [comment]
Thanks.

**Comment by rbeyer** [comment]
I got impatient and went ahead and just made templates via 66bf3817bff21dd937c7ba1ea5138a834b6d504c and 895c3b2e00f80aa0bcf0267972cf0c35b4bd1c82 to get them in place.  We can use the "usual" PR and review cycle for changes.
