### ISSUE TITLE
Add `raw` attribute to `Label` class

### ISSUE THREAD

**Issue by godber** [planetarypy/pvl#9]
I think the `Label` class needs a `raw` attribute that stores the complete, unaltered label text up to the final `END` block.

**Comment by rbeyer** [comment]
I'm not sure that it does, but that's probably a lack of imagination on my part.  How would you take advantage of that?  And what might be the benefit?  I suspect that since no one has followed up on this, there isn't a big demand for a feature like this.

This may also be overcome by changes in the recent 1.0.0-alpha merge.  Now, all of the user-facing functions in `__init__.py` convert anything they get into a string, and then pass that string through `pvl.loads()`.  There is *no* other way into the parser from the functions in `__init__.py`, and the parsers only take a string for their `parse()` argument.

So under this new architecture, the 'user' already has a string that is the equivalent of what you're talking about, so adding it to the *PVLModule* class seems a little redundant (sure, it may have other stuff in it past the final `END` block, so that *would* be a difference).  Alternately, if the user is using `pvl.load()` you might argue that the 'user' never sees a string, and that's true, but a 'user' could use the new `pvl.get_text_from()` to exract the same text that `pvl.load()` does, so they have a copy of that string, and then pass it on to `pvl.loads()` to get a *PVLModule* back.

**Comment by godber** [comment]
I wish I had written why I wanted this back then.  It was probably intended to be an emergency use only for cases where limitations in `pvl` lost information it could always be retrievable.

Feel free to close if it's no longer relevant and `pvl` is now guaranteed to preserve all of the input information.

**Comment by rbeyer** [comment]
Yeah, future me always wishes past me was better at documenting his thinking.  It always seems like he knew so much!

Since we can't recapture the use case, I'll close it.  Perhaps we'll run into it again.
